[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
	[plugins.inputs]
	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "/sitemap-index.xml"
