import { fileURLToPath } from 'node:url'

// Explicit routes avoid filesystem glob parsing for this small static CV.
// /en aliases preserve URLs generated by the previous translation integration.
export default function localizedRoutes() {
  return {
    name: 'cv-localized-routes',
    hooks: {
      'astro:config:setup': ({ injectRoute }) => {
        for (const locale of ['en', 'es', 'pt']) {
          for (const page of [
            'index',
            'experience',
            'projects',
            'skills',
            'print',
            'tests',
            'score'
          ]) {
            injectRoute({
              pattern: '/' + locale + (page === 'index' ? '' : '/' + page),
              entrypoint: fileURLToPath(new URL(`../src/pages/${page}.astro`, import.meta.url)),
              prerender: true
            })
          }
        }
      }
    }
  }
}
